spring.application.name=backend

# Puerto donde correrá el servidor de Java
server.port=8080

# Configuración de conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/CarritoComprasDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=asusrog7

# Driver y configuración de hibernate/JPA
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true